SELECT * FROM customer_behaviour.customer;

-- q1 .waht is the total revenue generated by males and femake customes?

SELECT 
    gender, SUM(purchase_amount) AS revenue
FROM
    customer
GROUP BY gender;


-- q2 . which customers used a discount but still spent  more than the average purchase amount?

SELECT 
    customer_id, purchase_amount
FROM
    customer
WHERE
    discount_applied = 'Yes'
        AND purchase_amount >= (SELECT 
            AVG(purchase_amount)
        FROM
            customer);
            
-- q3 which are the top 5 products with the highest average rating review?

SELECT 
    item_purchased,
    ROUND(AVG(review_rating), 2) AS average_rating
FROM
    customer
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC
LIMIT 5;

-- q4. comapre the average purchase amounts between standard and express shipping.

SELECT 
    shipping_type,
    ROUND(AVG(purchase_amount), 2) AS average_purchase_amount
FROM
    customer
WHERE
    shipping_type IN ('Standard' , 'Express')
GROUP BY shipping_type;

-- q5. do subscribers customers spend more ? compare average spend and total revenue 
-- between subscribers and non subscribers.

SELECT 
    subscription_status,
    COUNT(customer_id) AS total_customers,
    ROUND(AVG(purchase_amount), 2) AS avg_spend,
    ROUND(SUM(purchase_amount), 2) AS total_revenue
FROM
    customer
GROUP BY subscription_status
ORDER BY total_revenue , avg_spend DESC;

-- q6. which 5 products have the highest percentage of purchases with discounts applied?

SELECT 
    item_purchased,
    ROUND(100 * SUM(CASE
                WHEN discount_applied = 'Yes' THEN 1
                ELSE 0
            END) / COUNT(*),
            2) AS discount_rate
FROM
    customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

-- q7. segment customers into new ,returning and loyal based on their total
-- number of previous purchases ,and show the count of each segment

with customer_type as (
select customer_id,previous_purchases,
case 
	when previous_purchases = 1 then "New"
    when previous_purchases  between 2 and 10 then "Returning"
    else "Loyal"
    end as customer_segment
 from customer
 )
 select customer_segment ,count(*) as numbers_of_customers
 from customer_type
 group by customer_segment;
 
-- q8. waht are the top 3 most purchased products within each category?

with item_counts as (
select category,item_purchased,
count(customer_id) as total_orders,
row_number() over(partition by category order by count(customer_id) desc) as item_rank
 from customer
group by category,item_purchased
)
select item_rank,category,item_purchased,total_orders
from item_counts
where item_rank <=3;

-- q9. are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT 
    subscription_status, COUNT(customer_id) AS repeat_buyers
FROM
    customer
WHERE
    previous_purchases > 5
GROUP BY subscription_status;

-- q10. what is the revenue contribution of each age group?

select age_group,
sum(purchase_amount) as total_revenue  from customer
group by age_group
order by total_revenue desc;

